// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUEV9OoHs-aRCQfyoTr9r1g_3ur3UrU4s',
    appId: '1:249532807037:web:b9fe67a8e79c6a8ffe7e14',
    messagingSenderId: '249532807037',
    projectId: 'flutterauthen-25391',
    authDomain: 'flutterauthen-25391.firebaseapp.com',
    storageBucket: 'flutterauthen-25391.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACdRt8GJm9BcHjOrXilAp-1vuKQ4hjGWg',
    appId: '1:249532807037:android:33870c9592a013ecfe7e14',
    messagingSenderId: '249532807037',
    projectId: 'flutterauthen-25391',
    storageBucket: 'flutterauthen-25391.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6cR-kBVGDr3RY43fvs5NvJ4c805KblK0',
    appId: '1:249532807037:ios:2ee6e15154c43deefe7e14',
    messagingSenderId: '249532807037',
    projectId: 'flutterauthen-25391',
    storageBucket: 'flutterauthen-25391.appspot.com',
    iosBundleId: 'com.example.onboardScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6cR-kBVGDr3RY43fvs5NvJ4c805KblK0',
    appId: '1:249532807037:ios:17125eac76bff4affe7e14',
    messagingSenderId: '249532807037',
    projectId: 'flutterauthen-25391',
    storageBucket: 'flutterauthen-25391.appspot.com',
    iosBundleId: 'com.example.onboardScreen.RunnerTests',
  );
}
